### ISSUE TITLE
problem with method_put_detail()

### ISSUE THREAD

**Issue by ckot** [skies-io/django-rest-api#1]
Hi, first off, thanks for all your great work!  djangorestframework is _way_ more than I need, and the other alternatives don't seem to be able to deal with returning nested models in json, the way your project does.

Anyway, I've fully tested the GET and POST part of the api on my models, and they worked great.  I just started to test PUT requests, and got the following error:

```
Environment:

Request Method: PUT
Request URL: http://127.0.0.1:8000/api/1.0/experiment/1

Django Version: 1.8.3
Python Version: 3.2.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'expAdmin')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Traceback:
File "/home/ckot/venvs/django-tutalk-admin/lib/python3.2/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/ckot/venvs/django-tutalk-admin/lib/python3.2/site-packages/rest_api/API.py" in wrapper
   223.                 response = function(session, request, **kwargs)
File "/home/ckot/venvs/django-tutalk-admin/lib/python3.2/site-packages/rest_api/decorators.py" in must_be_connected_decorator
  42.         return function(self, session, request, **kwargs)

Exception Type: TypeError at /api/1.0/experiment/1
Exception Value: method_put_detail() takes exactly 5 arguments (4 given)
```

I'm using:

```
 @must_be_connected
 def method_put_detail(self, session, request, _id, data, **kwargs):
      #stuff
```

I took a peek at decorators.py, and I _think_ the problem _might_ be that  `must_be_connected()`
uses `function(self, session, request, **kwargs)` whereas both `get_data()` and `must_be_in_rights()` use `function(self, session, request, *args, **kwargs)`.

Either that or I'm doing something wrong...

**Comment by Dewep** [comment]
Hi.

First of all, thank you too for using our plugin.

For your problem, I have in fact, do some mistakes: I have not been completely consistent with my utilisation of positional arguments. Thus the arguments: `session`, `request` and `data` position-dependant and must be specified at each prototype.

So, I think you just replace your function declaration by (put the `data` argument before the `_id`):

``` python
@must_be_connected
@get_data(...)
def method_put_detail(self, session, request, data, _id, **kwargs):
    #stuff
```

To clarify it, I'm going to update the plugin, to put all parameters in keyword arguments.

I hope this will solve your problem. In all cases, don't hesitate to contact me again, it will be with pleasure that I will help you.

Thank you,
Aurélien.

**Comment by ckot** [comment]
Hi Aurélien,

I changed the params order and added the @get_data and it worked.  I’d rather not use @get_data so I can support PATCH, but seeing how I’m using this to create a CMS which will be the only thing manipulating the data (everything else will only be using GET) that should be ok.

Thanks for your quick response,

-Scott

**Comment by Dewep** [comment]
Yeah, you're right, `@get_data` is not really the best way to do this.
So I'll update this decorator, in the same time that to put all parameters in keyword arguments. I'll do this today.

Thank you,
Aurélien.

**Comment by ckot** [comment]
Just to make sure I’m understanding correctly, does this mean all of the methods will simply be method____(self, session, request, **kwargs), meaning that _id and data will need to be gotten from kwargs?

@get_data() is nice for POST & PUT, just not PATCH.  Then again, perhaps it should be up to the Model’s field validators.

**Comment by Dewep** [comment]
The arguments in the dictionary `kwargs` can be fetched automaticaly in python. After the update, you will be able to put only parameters you needed, and in the order that you want. Example (it will work for all methods called `method_*_*`):

``` python
def method_put_detail(self, _id, data, **kwargs):
    #stuff
```

To regard the `@get_data` and the PATCH method, I think to add a parameter `optional` (which could be a boolean or a list of fields).

**Comment by ckot** [comment]
Oh, I thought only _named_ parameters were automatically fetched by python.  Then again I’m not very familiar with python3.  

I had to setup a new virtualenv to use python3.  Prior to that, I followed example and in my prepend_urls() simply changed the super().prepend_url() to API.prepend_url(self) to make it work with python2, but it seemed that there was something else in your app which didn’t work with python2. I don’t remember if it was another call to super() or something else.  Then again, it might have been this issue and I just didn’t understand what the problem was.

**Comment by Dewep** [comment]
Hi,

I updated the plugin. As we said, I put all parameters in the keyword arguments.

I also updated the decorator `@get_data` to ameliorate his behavior in the PATCH method. You can see an example here: https://github.com/skies-io/django-rest-api/blob/6002a465610358d315da55bf60cdcf2cb12ed158/example/example/api_v1/project.py#L69L83

Thank you for your issue,
Aurélien.

**Comment by ckot** [comment]
sounds good. I'll try it out in a little bit. after looking at your changes in API.py though, shouldn't your example use:

method_patch_detail()
?

**Comment by Dewep** [comment]
You are right, thank you.
I edited the name of the method.
It was just a bad copy/paste from the previous method.
